name: 🐛 Bug Report
description: Report a bug or issue with SyndiCodex
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form as completely as possible.

  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: "A clear and concise description of what the bug is."
      placeholder: "Describe the bug..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: "Steps to Reproduce"
      description: "Please provide detailed steps to reproduce the issue."
      placeholder: |
        1. Run command `syndicodex ...`
        2. Enter input '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen?"
      placeholder: "Describe what you expected to happen..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      description: "What actually happened?"
      placeholder: "Describe what actually happened..."
    validations:
      required: true

  - type: dropdown
    id: command
    attributes:
      label: "Command"
      description: "Which SyndiCodex command were you using?"
      options:
        - onboarding
        - orchestrate
        - analyze
        - generate
        - chat
        - config
        - status
        - Other (please specify in description)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: "SyndiCodex Version"
      description: "What version of SyndiCodex are you using? (Run `syndicodex --version`)"
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: "Operating System"
      description: "What operating system are you using?"
      options:
        - macOS
        - Linux (Ubuntu)
        - Linux (Other)
        - Windows 10
        - Windows 11
        - Other (please specify)
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: "Node.js Version"
      description: "What version of Node.js are you using? (Run `node --version`)"
      placeholder: "v18.17.0"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Error Logs"
      description: "Please paste any error messages or logs (use `syndicodex --verbose` for detailed logs)"
      placeholder: "Paste error logs here..."
      render: text

  - type: textarea
    id: context
    attributes:
      label: "Additional Context"
      description: "Any additional information that might help us understand the issue"
      placeholder: "Add any other context about the problem here..."

  - type: checkboxes
    id: terms
    attributes:
      label: "Checklist"
      description: "Please confirm the following:"
      options:
        - label: "I have searched for existing issues before creating this one"
          required: true
        - label: "I have provided all the requested information"
          required: true
        - label: "I am using the latest version of SyndiCodex"
          required: false