name: ❓ Question
description: Ask a question about using SyndiCodex
title: "[Question]: "
labels: ["question"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have a question about SyndiCodex? We're here to help!

  - type: textarea
    id: question
    attributes:
      label: "Your Question"
      description: "What would you like to know about SyndiCodex?"
      placeholder: "How do I..."
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: "Question Category"
      description: "What area is your question about?"
      options:
        - "Getting Started"
        - "Installation & Setup"
        - "Autonomous Workflows"
        - "Code Generation"
        - "Code Analysis"
        - "Chat Interface"
        - "Configuration"
        - "Integrations"
        - "Troubleshooting"
        - "Best Practices"
        - "Performance"
        - "Security"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Context"
      description: "Provide any relevant context about your use case or what you're trying to achieve"
      placeholder: "I'm working on a project that..."

  - type: textarea
    id: attempted
    attributes:
      label: "What Have You Tried?"
      description: "Have you tried anything already? What happened?"
      placeholder: "I tried running... but..."

  - type: input
    id: version
    attributes:
      label: "SyndiCodex Version"
      description: "What version are you using? (Run `syndicodex --version`)"
      placeholder: "1.0.0"

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I have checked the documentation"
          required: true
        - label: "I have searched for similar questions"
          required: true